### ISSUE TITLE
'dash' label duplicate

### ISSUE THREAD

**Issue by alexkcode** [barseghyanartur/django-dash#11]
Getting 
```django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: dash```
exception when trying to migrate in django-1.7. Any fixes?
I have dash version 0.4.12

**Comment by barseghyanartur** [comment]
@alexkcode 

Can it be you've added some apps twice?

I'm now working on the version 1.5, which (among other functional improvements) does include quick start and some other missing documentation information. 

But, to answer your question, I have just tried it with a completely fresh project (installed Django 1.7.7 and created a test project from scratch) and it worked just fine - no errors. See the source here and tell me if there are any problems.

https://bitbucket.org/barseghyanartur/django-dash-example

**Comment by barseghyanartur** [comment]
@alexkcode 

FYI, 0.4.13 contains the hotfix for bug in `dash.contrib.plugins.dummy`. The example project mentioned above has been updated to work with that version. Everything runs smoothless.

**Comment by alexkcode** [comment]
OK will check my setup, thanks for the reply!

**Comment by alexkcode** [comment]
Seems to be fixed after pip uninstall and pip install, thanks
