### ISSUE TITLE
Unable to launch the dashboard - registration module missing

### ISSUE THREAD

**Issue by gitabhinav** [barseghyanartur/django-dash#17]
Hi, 
I installed django-dash using the pip command (also tried using the stable version from github). I followed the instructions in the readme document and created a dashboard and a plugin. However as soon as i try to launch the dashboard i get a 404 error http://localhost:8000/dashboard/account/login not found. I tried installing the examples but run into the same error. I am using python 3.6.1.

**Comment by barseghyanartur** [comment]
@gitabhinav:

Look, that part is covered with django-registration, which isn't a requirement of the django-dash, since any authentication system can be used.

So:

- Which version of Django do you use? You may want to check my [test requirements](https://github.com/barseghyanartur/django-dash/tree/master/examples/requirements).
- Check the [example settings](https://github.com/barseghyanartur/django-dash/blob/master/examples/example/settings/base.py#L277) (for django-registration config)

That's the path you should follow in order to have it running.

**Comment by gitabhinav** [comment]
Thank you for the quick response. 
I am using Django v1.11.4
I am very new to Django and so i would request you to break it down in simpler steps. 
The example settings that you have mentioned, should my urls.py look like that?

**Comment by barseghyanartur** [comment]
@gitabhinav:

To make it simple:

- Checkout entire project locally (git clone).
- Install the example requirements (for Django 1.11).
- Run the migrations.
- Run the server.

**Comment by barseghyanartur** [comment]
@gitabhinav:

Did it work for you?

**Comment by gitabhinav** [comment]
No. Unfortunately it hasn't. Still getting the same error. I was of the opinion that the registration page was inbuilt within the application. But that does not seem to be the case. I am working on making one now.

**Comment by barseghyanartur** [comment]
@gitabhinav:

There are way too many registration apps for Django to limit reusable apps to just one.

**Comment by gitabhinav** [comment]
Hi Artur, 
I did a clean install again, this time i followed the steps in your django_dash_example_app_installer.sh file. I am not getting the registration errors anymore. However the dashboard still won't run. I am getting 404 error no matter what url i try. 
"Using the URLconf defined in urls, Django tried these URL patterns, in this order:
^en/
^static\/(?P<path>.*)$
^media\/(?P<path>.*)$
The empty path didn't match any of these."
The url_pattern in \example\urls.py is empty so i am assuming that the parent file located at  \dash\urls.py is being used in this case. Is this correct?
Moreover, you have used a list "url_patterns_args" in \example\urls.py. What is this used for?

**Comment by barseghyanartur** [comment]
@gitabhinav:

Could you [run the demo locally](https://github.com/barseghyanartur/django-dash#run-demo-locally)?

After the steps, you should be able to visit the following URLs:

- http://localhost:8001/en/
- http://localhost:8001/en/dashboard/

Using the credentials mentioned.

**Comment by gitabhinav** [comment]
Hi Artur, 
I am trying to run it locally, but so far have barely managed the home page http://localhost:8001/en/
Some changes that i had to do to so far are:

- The templates section needs to be changed for Django 1.11 in base.py. I imported DJANGO_GTE_1_11 from nine.versions and have modified the code as follows: 
if (DJANGO_GTE_1_10 | DJANGO_GTE_1_11):
    TEMPLATES = ...
Not sure if this is the correct approach but this got me to the home page. 
- manage.py syncdb command is obsolete now. It took me some time to realize this as i am new to django. You may want to update the installer file. 

Currently i am getting 404 error on http://127.0.0.1:8001/en/accounts/login/?next=/en/dashboard/ page. I will try and solve this as well. I am feeling lucky today :)

**Comment by barseghyanartur** [comment]
@gitabhinav:

Demo installer works for me (just tested) with no change required. Anything else I need to know? OS, Python version? Otherwise, push your project to some (private) repository and give me the access. My BitBucket username is barseghyanartur.

**Comment by gitabhinav** [comment]
The OS that i am using is windows 10, Python version is 3.6.1 Django version is 1.11.4

**Comment by barseghyanartur** [comment]
@gitabhinav:

I'm running it with no problems on Windows.

I had to change the order of template loaders in base settings, though:

```python

                'loaders': [
                    'admin_tools.template_loaders.Loader',
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                    # 'django.template.loaders.eggs.Loader',
                ],
```

**Comment by gitabhinav** [comment]
Hi Artur, 
Thankyou! with this change the application is running now! It would be great if you could share a video or something for creating a dashboard using Django dash from scratch. I am pretty sure lot of people like me are looking for a python based solution. 
You may close this issue if you like.

**Comment by barseghyanartur** [comment]
@gitabhinav:

I'm glad it works for you now.
