### ISSUE TITLE
Getting going with django-dash

### ISSUE THREAD

**Issue by keepexploring** [barseghyanartur/django-dash#18]
Hi there,

Trying to get django-dash working locally. Have followed set up instructions for example project, but when I try to run and go to: http://127.0.0.1:8000/dashboard/

I just get a page not found 404 error (e.g. The current path, dashboard/, didn't match any of these). Have you any ideas why this might be occurring? I imagine I am missing something silly.

Thanks for your help,

**Comment by keepexploring** [comment]
Hi,

If I move all the urls from url_patterns_args to urlpatterns:

i.e. urlpatterns = [
            url(r'^dashboard/', include('dash.urls')),
            url(r'^dash/contrib/plugins/rss-feed/',
                include('dash.contrib.plugins.rss_feed.urls')),
            url(r'^administration/', include(admin.site.urls)),
            url(r'^news/', include('news.urls')),
            url(r'^accounts/', include('registration.backends.default.urls')),
            url(r'^$', TemplateView.as_view(template_name='home.html')),
            url(r'^', include('dash.contrib.apps.public_dashboard.urls')),
]

Then I, if I create a django admin user, I can login at http://127.0.0.1:8000/administration, and once logged in can create a dashboard for that user by going to http://127.0.0.1:8000/dashboard , but if I logout and try and go to http://127.0.0.1:8000/dashboard, I get the above 404 error - it rediverts to : http://127.0.0.1:8000/en/accounts/login/?next=/dashboard/ and says 'The current path, en/accounts/login/, didn't match any of these.' 

Have you got any thoughts on what the issue might be?

Thanks

**Comment by barseghyanartur** [comment]
@keepexploring:

Did you try [demo installer](https://github.com/barseghyanartur/django-dash/blob/master/examples/django_dash_example_app_installer.sh)?

**Comment by zhuyuecai** [comment]
the installer has bug. I have the same issue in this post. moreover. the installer will pip install the requirement for django 1.8, regardless which version of django my system currently has, them will fail in the subsequent steps. I manually change the commands and get it install. Then it seems to fail in create test data, due to some timezone warning. Or maybe I am not patient enough to wait for it to finish. Anyway, I can run the runserver,  but when I go to  http://127.0.0.1:8000/dashboard  without login, I get the same issue.

**Comment by barseghyanartur** [comment]
@keepexploring:

Demo installer works again (Django 1.11).

URLs used are:

- http://127.0.0.1:8000/en/administration/
- http://127.0.0.1:8000/en/dashboard/

Docs are updated.

Please, let me know if it works for you.

@zhuyuecai:

That's correct. Demo installer is supposed to be used for installing the demo. It's not an automated package installer.

Please, let me know if it works for you.

**Comment by barseghyanartur** [comment]
Closing this. Feel free to reopen if something is broken (again).

**Comment by pourmirzai** [comment]
I have the same Issue. going to /dashboard redirects me to 404 error. I need to first login at /admin then manually go back to /dashboard
