### ISSUE TITLE
Django 2.2 support

### ISSUE THREAD

**Issue by barseghyanartur** [barseghyanartur/django-dash#27]

**Comment by farridav** [comment]
I have this working with Django 3, is there a specific issue with 2.2 ?

**Comment by barseghyanartur** [comment]
Not specifically, actually, starting from 1.11 code migrations in Django are much simpler. Minimally, test suite shall be changed to include 2.2 and 3.0 to proclaim that they are supported. And pending deprecations shall be addressed (often, conditionally, using `django-nine`).

**Comment by barseghyanartur** [comment]
Done in master.
