### ISSUE TITLE
Getting an error on trying to register from Demo page

### ISSUE THREAD

**Issue by datatalking** [barseghyanartur/django-dash#28]
I am getting an error from the server below when I try to register for an account.

Is this the same "its full and needs emptying" issue that is reported in #19? 

`

Request Method: | POST
-- | --
https://django-dash.herokuapp.com/en/accounts/register/
1.6.11
ProgrammingError
permission denied for relation auth_user
/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/util.py in execute, line 53
/app/.heroku/python/bin/python
2.7.14
['/app',  '/app/.heroku/python/bin',  '/app',  '/app/.heroku/python/lib/python27.zip',  '/app/.heroku/python/lib/python2.7',  '/app/.heroku/python/lib/python2.7/plat-linux2',  '/app/.heroku/python/lib/python2.7/lib-tk',  '/app/.heroku/python/lib/python2.7/lib-old',  '/app/.heroku/python/lib/python2.7/lib-dynload',  '/app/.heroku/python/lib/python2.7/site-packages']
Wed, 17 Jul 2019 02:49:44 +0000

`

**Comment by mjlabe** [comment]
I've been getting this error for over a year.

**Comment by barseghyanartur** [comment]
Yep, that's because heroku does not allow more than 10,000 records per table. I have to manually reset db every time it reaches the limits. Use offline demo (quick to install).

**Comment by barseghyanartur** [comment]
Does anyone know a reliable service for hosting Python/Django demos without irritating (or sane) database restrictions. Otherwise, there shall be some automatic clean up made to keep demo working. In any case, help/input is highly appreciated.

**Comment by barseghyanartur** [comment]
Demo is working again (and upgraded to Django 3.1). Sorry for the delay.
