### ISSUE TITLE
using mongoengine with django-dash

### ISSUE THREAD

**Issue by jmrjrmv** [barseghyanartur/django-dash#5]
Hi,

Does this django package work with django mongoengine configuration ?

Best regards

**Comment by ttuti** [comment]
I am having problems with setup, I keep getting the following error:

```
 (dashboardenv) ttuti@KENBO-HWB01:~/dashboard/django-dash-stable/examples/example$ pip3 install https://github.com/barseghyanartur/django-dash/archive/stable.tar.gz
 Collecting https://github.com/barseghyanartur/django-dash/archive/stable.tar.gz
   Downloading https://github.com/barseghyanartur/django-dash/archive/stable.tar.gz (4.5MB)
    100% |################################| 4.5MB 135kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-y90f3no6-build/setup.py", line 136, in <module>
      for f in os.listdir(template_dir)]
     FileNotFoundError: [Errno 2] No such file or directory: 'src/dash/contrib/layouts/bootstrap3/templates/bootstrap3'

```

Please help me resolve this

**Comment by barseghyanartur** [comment]
@ttuti:

That's really strange. Bootstrap3 is something that is still in development and I myself can't reproduce that error. Could you provide some more information? What Python version are you using? What system? As much as possible, please.

**Comment by ttuti** [comment]
I am environment is: 
      python 3.4
      django 1.10.6
      Ubuntu 14.04.5 LTS

**Comment by barseghyanartur** [comment]
@ttuti:

I see. The stable tag is broken, but you can install it from PyPI.

```sh
pip install django-dash
```

The only place where it might be broken is the automated demo installer. Is that what you're trying to use?

**Comment by ttuti** [comment]
Yes, it is the automated demo installer that is failing.

**Comment by barseghyanartur** [comment]
@ttuti:

Clear. It's gonna be fixed tonight.

**Comment by barseghyanartur** [comment]
@ttuti:

Fixed.

**Comment by barseghyanartur** [comment]
Might be possible with https://github.com/nesdis/djongo
